# Generated by Django 3.1.6 on 2021-02-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuber_webpages', '0004_team_yt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emial', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('flink', models.CharField(max_length=100)),
                ('ilink', models.CharField(max_length=100)),
                ('tlink', models.CharField(max_length=100)),
                ('ylink', models.CharField(max_length=100)),
            ],
        ),
    ]
