# Generated by Django 3.1.6 on 2021-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuber_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tubercontact',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
