# Generated by Django 3.1.6 on 2021-02-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210204_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
